-- Run this in DBeaver against the ta15 database
USE ta15;

DELETE FROM exercise_recommendations;

-- Just Getting Started
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'standard', 'Seated Forward Lean', 5, 'Sit upright on a chair with feet flat on the floor. Slowly lean your upper body forward, sliding your hands toward your knees, keeping your back straight, then return upright.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'standard', 'Seated Chest Stretch', 8, 'Sit upright on a chair. Slowly move your arms out to the sides, opening your chest. Hold and breathe deeply.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'standard', 'Seated Knee Extensions', 5, 'Sit upright on a chair with feet flat on the floor. Slowly straighten one leg until parallel to the floor, hold briefly, then lower and switch legs.', NULL);

INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'lighter', 'Seated Forward Lean', 5, 'Sit upright on a chair with feet flat on the floor. Slowly lean your upper body forward, sliding your hands toward your knees, keeping your back straight, then return upright.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'lighter', 'Seated Chest Stretch', 8, 'Sit upright on a chair. Slowly move your arms out to the sides, opening your chest. Hold and breathe deeply.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'lighter', 'Seated Knee Extensions', 5, 'Sit upright on a chair with feet flat on the floor. Slowly straighten one leg until parallel to the floor, hold briefly, then lower and switch legs.', NULL);

INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'gentle_short', 'Seated Forward Lean', 5, 'Sit upright on a chair with feet flat on the floor. Slowly lean your upper body forward, sliding your hands toward your knees, keeping your back straight, then return upright.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'gentle_short', 'Seated Chest Stretch', 8, 'Sit upright on a chair. Slowly move your arms out to the sides, opening your chest. Hold and breathe deeply.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Just Getting Started', 'gentle_short', 'Seated Knee Extensions', 5, 'Sit upright on a chair with feet flat on the floor. Slowly straighten one leg until parallel to the floor, hold briefly, then lower and switch legs.', NULL);

-- Building Momentum
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'standard', 'Brisk Walking', 10, 'Begin at a comfortable pace then gradually increase speed. Swing your arms naturally and maintain a steady rhythm.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'standard', 'Sit-to-Stand', 8, 'Sit upright on a chair with feet flat on the ground. Lean slightly forward and push through your feet to stand, then lower back with control.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'standard', 'Arm Raises', 8, 'Stand or sit upright with arms at your sides. Slowly raise both arms out to the sides until they reach shoulder height, then gently lower them back down.', NULL);

INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'lighter', 'Brisk Walking', 10, 'Begin at a comfortable pace then gradually increase speed. Swing your arms naturally and maintain a steady rhythm.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'lighter', 'Sit-to-Stand', 8, 'Sit upright on a chair with feet flat on the ground. Lean slightly forward and push through your feet to stand, then lower back with control.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'lighter', 'Arm Raises', 8, 'Stand or sit upright with arms at your sides. Slowly raise both arms out to the sides until they reach shoulder height, then gently lower them back down.', NULL);

INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'gentle_short', 'Brisk Walking', 10, 'Begin at a comfortable pace then gradually increase speed. Swing your arms naturally and maintain a steady rhythm.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'gentle_short', 'Sit-to-Stand', 8, 'Sit upright on a chair with feet flat on the ground. Lean slightly forward and push through your feet to stand, then lower back with control.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Building Momentum', 'gentle_short', 'Arm Raises', 8, 'Stand or sit upright with arms at your sides. Slowly raise both arms out to the sides until they reach shoulder height, then gently lower them back down.', NULL);

-- Thriving
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'standard', 'Brisk Walking', 10, 'Begin at a comfortable pace then gradually increase speed. Swing your arms naturally and maintain a steady rhythm.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'standard', 'Mini Squats', 10, 'Stand with feet shoulder-width apart, arms forward. Slowly bend your knees and lower slightly, then push through your feet to return.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'standard', 'Standing Balance Hold', 8, 'Stand next to a chair for support. Lift one leg slightly in front and hold, then lower and switch legs.', NULL);

INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'lighter', 'Brisk Walking', 10, 'Begin at a comfortable pace then gradually increase speed. Swing your arms naturally and maintain a steady rhythm.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'lighter', 'Mini Squats', 10, 'Stand with feet shoulder-width apart, arms forward. Slowly bend your knees and lower slightly, then push through your feet to return.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'lighter', 'Standing Balance Hold', 8, 'Stand next to a chair for support. Lift one leg slightly in front and hold, then lower and switch legs.', NULL);

INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'gentle_short', 'Brisk Walking', 10, 'Begin at a comfortable pace then gradually increase speed. Swing your arms naturally and maintain a steady rhythm.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'gentle_short', 'Mini Squats', 10, 'Stand with feet shoulder-width apart, arms forward. Slowly bend your knees and lower slightly, then push through your feet to return.', NULL);
INSERT INTO exercise_recommendations (category_name, modifier_name, exercise_name, duration_minutes, instructions, notes) VALUES ('Thriving', 'gentle_short', 'Standing Balance Hold', 8, 'Stand next to a chair for support. Lift one leg slightly in front and hold, then lower and switch legs.', NULL);
